Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -10,14 +10,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Pulling the new commit
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
-          distribution: temurin
-          java-version: 17
+          distribution: 'temurin'
+          java-version: '17'
 
       - name: Set up Haxe
         uses: krdlab/setup-haxe@v2
@@ -58,10 +57,13 @@ jobs:
       - name: Build Android
         run: |
           mkdir -p build-logs
-          haxelib run lime build android -release -D HXCPP_M64 -D HXCPP_NO_PARALLEL > build-logs/build.log 2>&1
+          haxelib run lime build android -release -D HXCPP_M64 -D HXCPP_NO_PARALLEL 2>&1 | tee build-logs/build.log | grep -iE "error:|undefined reference|ld:|collect2:" || true
 
-      - name: Show last 100 lines of errors
-        run: tail -n 100 build-logs/build.log
+      - name: Upload build logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: Android Build Logs
+          path: build-logs/build.log
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
@@ -69,7 +71,7 @@ jobs:
           name: Android Build
           path: export/release/android/bin/*.apk
 
-      - name: Clear old cache
+      - name: Clear cache
         uses: actions/github-script@v7
         with:
           script: |
@@ -79,13 +81,14 @@ jobs:
             })
             for (const cache of caches.data.actions_caches) {
               if (cache.key == "cache-build-android") {
+                console.log('Clearing ' + cache.key + '...')
                 await github.rest.actions.deleteActionsCacheById({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   cache_id: cache.id,
                 })
               }
-            }
+           
 
       - name: Upload new cache
         uses: actions/cache@v4
